### ISSUE TITLE
グラフィック描画APIの選定

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#12]
オセロ実装によさげなAPIを探せ！！

**Comment by sinnchan** [comment]
候補
- [openFrameworks](https://openframeworks.cc/ja/) ← かっこいい
- [openGL](https://www.opengl.org/) ← どこにでも居るやつ
- [Vulkan](https://developer.android.com/ndk/guides/graphics/getting-started?hl=ja) ← GPUベンチマークガチ勢
- [Prossecing](https://processing.org/) ← シンプルでいい子

**Comment by Issei0804-ie** [comment]
[libGDX](http://westplain.sakuraweb.com/translate/libGDX/Articles/obviam/TutorialPart1.cgi)

**Comment by sinnchan** [comment]
libGDXでいきまほ

**Comment by Issei0804-ie** [comment]
gradleで動かしたいけど動かないから頑張ってるよよ

**Comment by Issei0804-ie** [comment]
[SurfaceView](https://www.google.com/search?q=SurfaceView+%E5%85%AC%E5%BC%8F&oq=SurfaceView+%E5%85%AC%E5%BC%8F&aqs=chrome..69i57.4089j0j1&sourceid=chrome&ie=UTF-8)

**Comment by sinnchan** [comment]
3Dじゃなくて、２Dアニメーション実装すれば楽なんじゃないかと思い始めた

**Comment by sinnchan** [comment]
https://qiita.com/BingSyu/items/bd1278feab270501330b

**Comment by sinnchan** [comment]
さばっぴょにSVGアニメーションを作ってもらうことにした
