### ISSUE TITLE
オンライン対戦の仕様

### ISSUE THREAD

**Issue by Issei0804-ie** [Issei0804-ie/Uhyo#14]

**Comment by Issei0804-ie** [comment]
こんな感じでどうすか
![online_battle](https://user-images.githubusercontent.com/52270000/72775584-52a8cb00-3c52-11ea-8060-14f22957b356.png)

**Comment by sinnchan** [comment]
![Dkt3fnqUcAAVaUN](https://user-images.githubusercontent.com/55493336/72903310-5a5e9180-3d70-11ea-9b6c-96284bc21b49.jpg)

**Comment by Issei0804-ie** [comment]
エンドポイント名(仮称)

#ルームを作る
/api_makeRoom

#部屋に入る
/api_JoinRoom

部屋を選ぶ
/api_SelectRoom

先手後手はこれらが完成次第触るー

**Comment by Issei0804-ie** [comment]
リポジトリ移動に伴いクローズ
