### ISSUE TITLE
オンライン対戦の画面遷移

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#23]
まだ

**Comment by sinnchan** [comment]
UXは米に委譲しました

**Comment by Issei0804-ie** [comment]
@komekomeclub5 
ここら辺の issue を片付けてくれる（wikiにあるならその旨を告げる、リンクを貼る）と嬉しい！

**Comment by komekomeclub5** [comment]
![スクリーンショット 2020-03-16 0 09 12](https://user-images.githubusercontent.com/56760463/76704173-63d5fb80-671a-11ea-8994-a29cd2ebdd50.png)
