### ISSUE TITLE
画面遷移作成[オンライン抜き][プレイ画面まで]

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#30]
# くわしく
タイトル通り

**Comment by komekomeclub5** [comment]
![ひとり対戦](https://user-images.githubusercontent.com/56760463/75046981-66717680-5509-11ea-832e-62209360c1bb.png)
![ローカル二人対戦　案２](https://user-images.githubusercontent.com/56760463/75046985-67a2a380-5509-11ea-93ee-9b7807e5f775.png)
![最初の画面 –](https://user-images.githubusercontent.com/56760463/75046987-683b3a00-5509-11ea-8278-dfa447a85dd2.png)

**Comment by sinnchan** [comment]
ぱっと思いついたつっこみ↓
---
- やっぱり各画面の導線が見れるようにしてほしい。（みんなが見れるようなフォーマットで）
- 一枚目
  - 黒と白のあなたとYOU
  - 一時停止らしきボタンを押した際の動作
- 二枚目
  - 一時停止らしきボタンを押した際の動作（一枚目と同じ？
  - 黒と白の文字は駒の色を見ればわかるので要らないはず（理由があるならすまん）
- 三枚目
  - オンライン対戦の近くの人とふたりプレイは同じでいいはず

**Comment by komekomeclub5** [comment]
![スクリーンショット 2020-03-15 23 54 49](https://user-images.githubusercontent.com/56760463/76703935-d6de7280-6718-11ea-87ed-88c1f5bf366f.png)

ふたりプレイのときは"ふたり"ボタンを押したらすぐ対局画面に行きます。
オンライン対局の先手後手はランダムで設定するのですぐ対局画面に行きます。
