### ISSUE TITLE
タイトル画面作成（デザイン）

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#31]
# くわしく
タイトル画面を完成形までもっていく

**Comment by komekomeclub5** [comment]
![オセロロゴ4](https://user-images.githubusercontent.com/56760463/76704101-0b9ef980-671a-11ea-818e-dff0ee523ad2.png)
![最初の画面](https://user-images.githubusercontent.com/56760463/76704102-0e015380-671a-11ea-923e-354c21bc1eba.png)

**Comment by sinnchan** [comment]
オンライン対戦ボタンは押しても何もレスポンス返さないかんじ？

**Comment by komekomeclub5** [comment]
何も考えずに返さないようにしてました
オンライン対戦ができるのであれば上と同じ白にしてくれれば大丈夫です

**Comment by komekomeclub5** [comment]
![スクリーンショット 2020-03-19 0 05 52](https://user-images.githubusercontent.com/56760463/76975098-684a2080-6975-11ea-9a5a-4199ec38322a.png)
修正しました
