### ISSUE TITLE
プレイ画面作成（デザイン）

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#33]
# くわしく
実際に表示されるデザインまで作りこむ

**Comment by komekomeclub5** [comment]
![対局1](https://user-images.githubusercontent.com/56760463/76704092-f6c26600-6719-11ea-887d-1f6e6c43dd83.png)
![対局2](https://user-images.githubusercontent.com/56760463/76704093-f7f39300-6719-11ea-8628-9ae062cd3f86.png)

**Comment by sinnchan** [comment]
一人プレイで白を選んだ場合、
”あなた”と”相手”の文字を入れ替えるのか、下のカウンターを入れ替えるのかどっち？

**Comment by sinnchan** [comment]
二人プレイでも上の～の番の文字は「黒の番」と「白の番」のままででいいんでしょうか？

**Comment by komekomeclub5** [comment]
一人プレイのときは”あなた”と”相手”の文字を入れ替えます。

二人プレイは「黒の番」と「白の番」のほうが一番わかりやすいと思うので、
そのままで大丈夫です。

忘れていましたが、二人プレイのとき”あなた”と”相手”は混乱するので、
表示しないほうがいいです。
