### ISSUE TITLE
必要な画面の洗い出し

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#35]
# くわしく
そもそもアプリの構成に必要な画面が把握できていないので洗い出す

**Comment by sinnchan** [comment]
現時点でざっくり洗い出せている奴↓

- タイトル画面
- AI強さ設定
- 先攻後攻選択（↑と画面一緒にするかはUXしだい
- オンライン対戦（待機）
- プレイ画面
  - 一時停止（オンライン対戦では項目変わるはず
- リザルト

**Comment by sinnchan** [comment]
ほかにもあればコメントくだしい

**Comment by komekomeclub5** [comment]
必要な画面まとめました
![スクリーンショット 2020-03-15 23 54 49](https://user-images.githubusercontent.com/56760463/76703888-7f400700-6718-11ea-84b7-b0b3c65b1456.png)

**Comment by sinnchan** [comment]
お疲れ様です。

ルール説明の文言がまだっぽいのでIssue立てときました→ #48

**Comment by sinnchan** [comment]
一応洗い出せたのでいったん閉じます
