### ISSUE TITLE
リザルト画面（デザイン）

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#40]
# くわしく
仕様作成

**Comment by komekomeclub5** [comment]
![リザルト](https://user-images.githubusercontent.com/56760463/76704040-959a9280-6719-11ea-9e5e-c9f809bd84c7.png)

**Comment by sinnchan** [comment]
終わるボタンはアプリ終了かタイトルに戻るのかどっちでしょう？
タイトルに戻る認識ですが。。

**Comment by komekomeclub5** [comment]
タイトルに戻るです。
ユーザーが混乱する可能性があるので"タイトルに戻る"とかにした方がいいと思います。
UIの修正が必要であれば準備します

**Comment by komekomeclub5** [comment]
![スクリーンショット 2020-03-19 0 06 44](https://user-images.githubusercontent.com/56760463/76975175-8748b280-6975-11ea-9b2e-8eab2b7cd6f1.png)
修正しました
