### ISSUE TITLE
ルール説明ダイアログの文言作成

### ISSUE THREAD

**Issue by sinnchan** [Issei0804-ie/Uhyo#48]
# くわしく
こいつの文言考えよう↓
![ポップアップ画面　ルール](https://user-images.githubusercontent.com/56760463/76704574-48b8bb00-671d-11ea-9148-766e74feb52f.png)

**Comment by komekomeclub5** [comment]
準備しておきます
今忙しいので1週間はかかるかもしれないです
なるべく早めに対応します

**Comment by komekomeclub5** [comment]
石を黒白交互に挟むように打ってひっくり返し、
最後に石が多い方が勝ちとなります。
両プレイヤーは白と黒どちらかを選びます。
黒が先行、白が後攻となります。
